runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: level5.app

- url: /static
  static_dir: static

- url: /level5/frame/signup.html
  static_files: signup.html

- url: /level5/frame/confirm.html
  static_files: confirm.html

- url: /level5/frame/welcome.html
  static_files: welcome.html